/// Environment configuration for compile-time settings.
///
/// Values are injected via `--dart-define` flags during build:
/// ```bash
/// flutter build apk \
///   --dart-define=BOOTSTRAP_URL=https://qa.example.com \
///   --dart-define=SIGNALING_URL=wss://qa.example.com:8080 \
///   --dart-define=ENV=qa \
///   --dart-define=VERSION=1.0.0
/// ```
library;

import 'package:flutter/foundation.dart' show kReleaseMode;

/// Environment configuration using compile-time constants.
///
/// These values are baked into the app at build time and cannot be changed
/// at runtime. Use for CI/CD builds targeting different environments.
class Environment {
  Environment._();

  /// Bootstrap/discovery server URL (Cloudflare Workers).
  ///
  /// Used to discover available signaling servers.
  /// Override with `--dart-define=BOOTSTRAP_URL=<url>`
  static const String bootstrapUrl = String.fromEnvironment(
    'BOOTSTRAP_URL',
    defaultValue: '',
  );

  /// Direct signaling server URL (WebSocket).
  ///
  /// If set, bypasses server discovery and connects directly.
  /// Override with `--dart-define=SIGNALING_URL=<url>`
  static const String signalingUrl = String.fromEnvironment(
    'SIGNALING_URL',
    defaultValue: '',
  );

  /// Diagnostics server URL (Cloudflare Workers).
  ///
  /// Where crash reports and heartbeats are sent.
  /// Override with `--dart-define=DIAGNOSTICS_URL=<url>`
  static const String diagnosticsUrl = String.fromEnvironment(
    'DIAGNOSTICS_URL',
    defaultValue: '',
  );

  /// Whether a diagnostics URL was provided.
  static bool get hasDiagnosticsUrl => diagnosticsUrl.isNotEmpty;

  /// Environment name (production, qa, dev).
  ///
  /// Override with `--dart-define=ENV=<env>`
  static const String env = String.fromEnvironment(
    'ENV',
    defaultValue: 'production',
  );

  /// App version string.
  ///
  /// Override with `--dart-define=VERSION=<version>`
  static const String version = String.fromEnvironment(
    'VERSION',
    defaultValue: '',
  );

  /// Build number for this release.
  ///
  /// Override with `--dart-define=BUILD_NUMBER=<number>`
  static const String buildNumber = String.fromEnvironment(
    'BUILD_NUMBER',
    defaultValue: '',
  );

  /// Signed build token for app attestation.
  ///
  /// Base64-encoded JSON containing version, platform, build_hash,
  /// timestamp, and signature. Generated by CI during release builds.
  /// Override with `--dart-define=BUILD_TOKEN=<base64>`
  static const String buildToken = String.fromEnvironment(
    'BUILD_TOKEN',
    defaultValue: '',
  );

  /// Whether to use TUF metadata verification instead of legacy single-key signing.
  /// Set via --dart-define=USE_TUF_METADATA=true
  static const bool useTufMetadata = bool.fromEnvironment(
    'USE_TUF_METADATA',
    defaultValue: false,
  );

  /// Base URL for fetching TUF metadata (e.g., 'https://bootstrap.zajel.example.com').
  /// Defaults to the same base URL used for bootstrap.
  static const String tufMetadataBaseUrl = String.fromEnvironment(
    'TUF_METADATA_BASE_URL',
    defaultValue: '',
  );

  /// Whether running in E2E test mode.
  ///
  /// Override with `--dart-define=E2E_TEST=true`
  static const bool isE2eTest = bool.fromEnvironment('E2E_TEST');

  /// Whether running Dart integration tests (flutter test integration_test/).
  ///
  /// When true, skips signaling server connection to avoid network
  /// dependencies and slow timeouts. Tests can override pairingCodeProvider
  /// to inject mock pairing codes without them being overwritten.
  /// Override with `--dart-define=INTEGRATION_TEST=true`
  static const bool isIntegrationTest =
      bool.fromEnvironment('INTEGRATION_TEST');

  /// Verify that E2E_TEST is not accidentally enabled in release builds.
  ///
  /// Call this during app startup. Throws in release mode if E2E_TEST is true.
  /// Uses a runtime check (not assert) because assert is stripped from release.
  static void assertNoE2eTestInRelease() {
    // Allow E2E in QA release builds (CI uses --release --dart-define=ENV=qa)
    if (kReleaseMode && isE2eTest && !isQA) {
      throw StateError(
        'FATAL: E2E_TEST=true must never be used in production release builds. '
        'This flag disables security features including pair request approval.',
      );
    }
  }

  /// Whether running in QA environment.
  static bool get isQA => env == 'qa';

  /// Whether running in production environment.
  static bool get isProduction => env == 'production';

  /// Whether running in development environment.
  static bool get isDev => env == 'dev';

  /// Whether a custom bootstrap URL was provided.
  static bool get hasCustomBootstrapUrl => bootstrapUrl.isNotEmpty;

  /// Whether a direct signaling URL was provided (bypasses discovery).
  static bool get hasDirectSignalingUrl => signalingUrl.isNotEmpty;

  /// Full version string including build number.
  static String get fullVersion {
    if (buildNumber.isNotEmpty) {
      return '$version+$buildNumber';
    }
    return version.isNotEmpty ? version : 'dev';
  }
}
