import 'dart:convert';

/// Represents a signed build token embedded at compile time.
///
/// The build token is generated by CI during the release build process.
/// It contains metadata about the build and a signature proving it was
/// produced by an authorized build pipeline.
///
/// Embedded via `--dart-define=BUILD_TOKEN=<base64-encoded-json>`.
class BuildToken {
  /// App version string (e.g., "1.2.0").
  final String version;

  /// Target platform (e.g., "android", "ios", "linux", "windows", "macos", "web").
  final String platform;

  /// SHA-256 hash of the release binary.
  final String buildHash;

  /// Unix timestamp (milliseconds) when the build was produced.
  final int timestamp;

  /// Ed25519 signature over the token payload, base64-encoded.
  final String signature;

  const BuildToken({
    required this.version,
    required this.platform,
    required this.buildHash,
    required this.timestamp,
    required this.signature,
  });

  /// Parse a build token from a base64-encoded JSON string.
  ///
  /// Returns null if the input is empty or malformed.
  static BuildToken? fromBase64(String base64String) {
    if (base64String.isEmpty) return null;
    try {
      final jsonString = utf8.decode(base64Decode(base64String));
      final json = jsonDecode(jsonString) as Map<String, dynamic>;
      return BuildToken.fromJson(json);
    } catch (_) {
      return null;
    }
  }

  factory BuildToken.fromJson(Map<String, dynamic> json) {
    return BuildToken(
      version: json['version'] as String? ?? '',
      platform: json['platform'] as String? ?? '',
      buildHash: json['build_hash'] as String? ?? '',
      timestamp: json['timestamp'] as int? ?? 0,
      signature: json['signature'] as String? ?? '',
    );
  }

  Map<String, dynamic> toJson() => {
        'version': version,
        'platform': platform,
        'build_hash': buildHash,
        'timestamp': timestamp,
        'signature': signature,
      };

  /// Encode to base64 JSON for embedding.
  String toBase64() {
    return base64Encode(utf8.encode(jsonEncode(toJson())));
  }

  /// Whether this token has all required fields populated.
  bool get isValid =>
      version.isNotEmpty &&
      platform.isNotEmpty &&
      buildHash.isNotEmpty &&
      timestamp > 0 &&
      signature.isNotEmpty;

  @override
  String toString() =>
      'BuildToken(version=$version, platform=$platform, timestamp=$timestamp)';
}
